#!/usr/bin/python3


card_list = [
        ("Stepping on a piece of lego while barefooted", 1.0),
        ("Cry while cutting onions", 2.0),
        ("Guitar pick lost inside sound hole of guitar", 3.0),
        ("Sneezed on by fellow commuter", 4.5),
        ("Stub toe on chair leg", 5.0),
        ("Wrong order", 6.0),
        ("Slip on icy sidewalk", 6.5),
        ("0% battery", 8.0),
        ("Bunk with heavy snorer", 9.0),
        ("Wet bed", 10.0),
        ("Step in huge puddle", 11.0),
        ("Lectured by racist grandparent", 11.5),
        ("No signal", 12.0),
        ("Beaten in an arm wrestle by 6-year-old girl", 13.5),
        ("Rudely awoken by roommate's loud music", 14.0),
        ("Parking fine", 15.0),
        ("Spill wine on best dress", 17.0),
        ("Scammed in Paris", 18.0),
        ("Worm in burger", 20.0),
        ("Stung by bee", 21.0),
        ("Pants fall down in public", 21.5),
        ("Favourite team is relegated", 22.0),
        ("Severely hungover", 23.0),
        ("Save file corrupted", 24.0),
        ("Flat tire", 24.5),
        ("Lose house keys", 25.0),
        ("No hot water", 26.0),
        ("Drunk text ex", 26.5),
        ("Ignored by crush", 27.0),
        ("Forget lines in play", 28.0),
        ("Dog bites you", 29.0),
        ("Migraine", 30.0),
        ("Coworker eats your lunch", 30.5),
        ("\"Nice guy\" hits on you", 31.0),
        ("Period pain", 31.5),
        ("Shat on by bird", 32.0),
        ("Ingrown toenail", 32.5),
        ("Broken leg", 33.0),
        ("Drop phone in toilet", 34.0),
        ("Cease & desist", 35.0),
        ("Unwillingly caught in moshpit", 35.5),
        ("Payment is \"exposure\"", 36.0),
        ("Victim of ransomware", 36.5),
        ("You're fired!", 37.0),
        ("Accidentally consume cat food", 38.5),
        ("Commuter vomits on you", 39.0),
        ("Dumped via text message", 40.0),
        ("Caught up in pyramid scheme", 41.0),
        ("Alone, drunk, lost in unfamiliar city", 42.0),
        ("Bedbugs", 43.0),
        ("Creepy homeless guy follows you home", 45.0),
        ("Getting audited", 47.0),
        ("Take wrong meds", 47.5),
        ("Deported", 48.0),
        ("Mugged", 49.0),
        ("Diorrhea while on the Eurostar", 50.0),
        ("COVID-19 positive", 53.0),
        ("Peak of Nordic winter, heating broken", 55.0),
        ("Saw off finger", 57.0),
        ("See girl from The Ring in your bathroom mirror at midnight", 59.0),
        ("Carjacked!", 60.0),
        ("Insomnia", 61.0),
        ("Evicted!", 64.0),
        ("Rap battle with Eminem in front of 10,000 people", 65.0),
        ("Pet dog dies", 66.0),
        ("Favourite band cancels last minute", 67.0),
        ("Attacked by swarm of wasps", 68.0),
        ("Discover dead horse in your bed", 69.0),
        ("Bring knife to a gun fight", 70.0),
        ("Hitch last minute ride on the Titanic", 71.0),
        ("Team loses world cup final, you're to blame", 72.0),
        ("Extorted by local mafia", 73.0),
        ("Doxxed", 74.0),
        ("Dive into shallow water", 75.0),
        ("Target of online witch hunt", 76.0),
        ("Bankruptcy", 77.0),
        ("IS places bounty on your head", 78.0),
        ("Unplanned/unwanted pregnancy", 79.0),
        ("Partner leaves you for your best friend", 80.0),
        ("Hunted down by Liam Neeson", 81.0),
        ("Doctor amputates the wrong arm", 82.0),
        ("Drafted into war", 83.0),
        ("Left at the altar", 84.0),
        ("Get in a bar fight with Mike Tyson", 85.0),
        ("House mistakenly bulldozed", 85.5),
        ("Chronic depression", 86.0),
        ("Shark takes a bite out of your leg", 87.0),
        ("Crushed by scaffolding on morning commute", 88.0),
        ("Imprisoned for life", 89.0),
        ("Terminal cancer", 89.5),
        ("Squashed by a garbage truck", 90.0),
        ("Buried alive", 91.0),
        ("Hit by oncoming train", 92.0),
        ("Shot 9 times", 93.0),
        ("Stranded on desert island", 94.0),
        ("Framed for murder of your entire family", 95.0),
        ("You're in The Matrix, everything you ever knew was a lie", 96.0),
        ("Addicted to meth", 97.0),
        ("Eaten alive by a family of bears", 99.0),
        ("Crucified", 100.0)
    ]
